application: ourtweetspot
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
  
- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
    
- url: .*
  script: bootstrap.py
  

